### ISSUE TITLE
Decide main voltage and sub voltages + design the circuits

### ISSUE THREAD

**Issue by Lauwy222** [Alset-Innovations/Schem#3]
```The motor controller must be able to continuously turn a 24 V, 78 W BLDC motor in a closed loop configuration using hall sensor feedback```

**Comment by Lauwy222** [comment]
24V naar 5V met behulp van de `slvsb56c` en een filter om de rimpel spanning weg te filteren, daarna met een regulator naar 3.3 voor de STM32.

**Comment by Lauwy222** [comment]
| 24V         	| 5V                       	| 3.3V                	|
|-------------	|--------------------------	|---------------------	|
| 6×MOSFET    	| Hall sensor              	| Hall sensor pull up 	|
| Gate Driver 	| Voltage regulator (3.3V) 	| STM32               	|
|             	| Raspberry pi + screen    	|                     	|

**Comment by marnix707** [comment]
5 v naar 3.3 volt met UA78M33C (0.3nf met 0.1nf)

**Comment by Lauwy222** [comment]
![Image](https://github.com/Alset-Innovations/Schem/assets/24575818/047f11ed-2334-4f69-9d8a-f2e5ab88c619)
